views/empleado_view.py
from app import db
from models import Empleado, Sucursal
from flask import Blueprint, request, jsonify

from schemas import EmpleadoSchema, SucursalSchema

empleado_bp = Blueprint('empleado', __name__)


@empleado_bp.route("/empleados", methods=['GET', 'POST'])
def empleado():
    empleados = Empleado.query.all()
    sucursal = Sucursal.query.all()
    return jsonify({
        'empleados': EmpleadoSchema(many=True).dump(empleados),
        'sucursales': SucursalSchema(many=True).dump(sucursal)
    })


@empleado_bp.route("/empleados/crear", methods=['POST'])
def crear_empleado():
    datos = request.json

    if datos:
        nombre = datos.get("nombre")
        dni = datos.get("dni")
        sucursal_id = datos.get("sucursal_id")
        cargo = datos.get("cargo")
        telefono = datos.get("telefono")
        email = datos.get("email")
        direccion = datos.get("direccion")

        nuevo_empleado = Empleado(
            nombre=nombre,
            dni=dni,
            sucursal_id=sucursal_id,
            cargo=cargo,
            telefono=telefono,
            email=email,
            direccion=direccion
        )
        db.session.add(nuevo_empleado)
        db.session.commit()
        return jsonify({'Mensaje': 'Empleado cargado con exito.'})

    else:
        return jsonify({'Mensaje': 'Error al cargar el nuevo empleado'})


@empleado_bp.route("/empleados/editar/<int:id>", methods=['GET','POST'])
def editar_empleado(id):
    empleado = Empleado.query.get_or_404(id)

    if request.method == "GET":
        return jsonify(EmpleadoSchema().dump(empleado))

    else:
        datos = request.json
        if datos:
            empleado.nombre = datos.get("nombre")
            empleado.sucursal_id = datos.get("sucursal_id")
            empleado.cargo = datos.get("cargo")
            empleado.dni = datos.get("dni")
            empleado.telefono = datos.get("telefono")
            empleado.email = datos.get("email")
            empleado.direccion = datos.get("direccion")

            db.session.commit()
            return jsonify({'Mensaje': 'Empleado actualizado con exito.'})

        else:
            return jsonify({'Mensaje': 'Error al actualizar el empleado.'})

@empleado_bp.route("/empleados/delete/<int:id>", methods=['GET','POST'])
def eliminar_empleado(id):
    empleado = Empleado.query.filter_by(id=id).first()
    db.session.delete(empleado)
    db.session.commit()
    return jsonify({'Mensaje': 'Empleado eliminado con exito.'})

templates/empleados/editar_empleado.html
{% extends 'base.html'%}
{% block tittle %}
{% endblock %}
{% block content %}
<div class="container-form container">
    <form action="{{ url_for('empleado.editar_empleado', id=empleado.id) }}" method="post">
        <div>
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" value={{ empleado.nombre }}>
        </div>
        <div>
            <label for="dni" class="form-label">DNI</label>
            <input type="number" class="form-control" name="dni" id="dni" value={{ empleado.dni }}>
        </div>
        <div>
            <label for="telefono" class="form-label">Telefono</label>
            <input type="number" class="form-control" name="telefono" id="telefono" value={{ empleado.telefono }}>
        </div>
        <div>
            <label for="direccion" class="form-label">Direccion</label>
            <input type="text" class="form-control" name="direccion" id="direccion" value={{ empleado.direccion }}>
        </div>
        <div>
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" name="email" id="email" value={{ empleado.email }}>
        </div>
        <div>
            <label for="cargo" class="form-label">Cargo</label>
            <select name="cargo" class="form-select" id="cargo">
                <option>{{ empleado.cargo }}</option>
                <option value="gerente">Gerente</option>
                <option value="empleado">Empleado</option>
                <option value="vendedor">Vendedor</option>
                <option value="repartidor">Repartidor</option>
            </select>
        </div>
        <div>
            <label for="sucursal" class="form-label">Sucursal</label>
            <select name="sucursal" class="form-select" id="sucursal">
                {% for sucursal in sucursales %}
                    <option value="sucursal.id">{{ sucursal.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <button class="btn btn-primary mt-3" type="submit">Agregar Empleado</button>
    </form>
</div>
{%endblock%}

templates/empleados/empleados.html
{% extends 'base.html'%}
{% block tittle %}<h4>Productos</h4>{% endblock %}
{% block content %}
<div class="productos-container">
    <div class="container-tabla">
        <input type="text" placeholder="Buscar...">
        <table class="table table-striped">
            <thead>
                <th>Nombre</th>
                <th>DNI</th>
                <th>Telefono</th>
                <th>Direccion</th>
                <th>Email</th>
                <th>Cargo</th>
                <th>Sucursal</th>
            </thead>
            <tbody class="table-group-divider">
                {% for empleado, sucursal in empleados %}
                <tr>
                    <td>{{empleado.nombre}}</td>
                    <td>{{empleado.dni}}</td>
                    <td>{{empleado.telefono}}</td>
                    <td>{{empleado.direccion}}</td>
                    <td>{{empleado.email}}</td>
                    <td>{{empleado.cargo}}</td>
                    <td>{{sucursal.nombre}}</td>
                    <td><a href="{{ url_for('empleado.editar_empleado', id=empleado.id) }}" class="btn btn-success">Editar</a></td>
                    <td><a href="{{ url_for('empleado.eliminar_empleado', id=empleado.id) }}" class="btn btn-danger">Eliminar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container-form form">
        <form action="empleados/crear", method="post">
            <div>
                <label for="nombre" class="form-label">Nombre</label>
                <input type="text" class="form-control" name="nombre" id="nombre">
            </div>
            <div>
                <label for="dni" class="form-label">DNI</label>
                <input type="number" class="form-control" name="dni" id="dni">
            </div>
            <div>
                <label for="telefono" class="form-label">Telefono</label>
                <input type="number" class="form-control" name="telefono" id="telefono">
            </div>
            <div>
                <label for="direccion" class="form-label">Direccion</label>
                <input type="text" class="form-control" name="direccion" id="direccion">
            </div>
            <div>
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" name="email" id="email">
            </div>
            <div>
                <label for="cargo" class="form-label">Cargo</label>
                <select name="cargo" class="form-select" id="cargo">
                    <option value="gerente">Gerente</option>
                    <option value="empleado">Empleado</option>
                    <option value="vendedor">Vendedor</option>
                    <option value="repartidor">Repartidor</option>
                </select>
            </div>
            <div>
                <label for="sucursal" class="form-label">Sucursal</label>
                <select name="sucursal" class="form-select" id="sucursal">
                    {% for sucursal in sucursales %}
                        <option value={{ sucursal.id }}>{{ sucursal.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            <button class="btn btn-primary mt-3" type="submit">Agregar Empleado</button>
        </form>
    </div>
</div>
{%endblock%}