views/producto_view.py
from app import db
from models import Producto, Modelo, Proveedor, Categoria
from flask import Blueprint, jsonify, request
from schemas import ProductoSchema, ModeloSchema, ProveedorSchema, CategoriaSchema


productos_bp = Blueprint('productos', __name__)


@productos_bp.route("/productos", methods=['GET'])
def productos():
    productos = Producto.query.all()
    modelos = Modelo.query.all()
    proveedor = Proveedor.query.all()
    categoria = Categoria.query.all()
    return jsonify({
        "modelos": ModeloSchema(many=True).dump(modelos), 
        "proveedores":ProveedorSchema(many=True).dump(proveedor), 
        "categorias":CategoriaSchema(many=True).dump(categoria), 
        "productos":ProductoSchema(many=True).dump(productos)
        })

@productos_bp.route("/productos/crear", methods=['POST'])
def crear_producto():
    datos = request.get_json()
    print(datos)

    if datos:
        nombre = datos.get("nombre")
        precio = datos.get("precio")
        stock = datos.get("stock")
        modelo_id = datos.get("modelo_id")
        categoria_id = datos.get("categoria_id")
        proveedor_id = datos.get("proveedor_id")

        nuevo_producto = Producto(
            nombre=nombre,
            precio=precio,
            stock=stock,
            modelo_id=int(modelo_id),
            categoria_id=int(categoria_id),
            proveedor_id=int(proveedor_id)
        )
        db.session.add(nuevo_producto)
        db.session.commit()
        return jsonify({'Mensaje': 'Producto cargado con exito.'})

    else:
        return jsonify({'Mensaje': 'Error al cargar el nuevo producto'})

@productos_bp.route("/productos/editar/<int:id>", methods=['GET','POST'])
def editar_producto(id):
    producto = Producto.query.get_or_404(id)

    if request.method == "GET":
        return jsonify(ProductoSchema().dump(producto))

    else:
        datos = request.json
        if datos:
            producto.nombre = datos.get("nombre")
            producto.precio = datos.get("precio")
            producto.stock = datos.get("stock")
            producto.modelo_id = datos.get("modelo_id")
            producto.categoria_id = datos.get("categoria_id")
            producto.proveedor_id = datos.get("proveedor_id")

            db.session.commit()
            return jsonify({'Mensaje': 'Producto actualizado con exito.'})

        else:
            return jsonify({'Mensaje': 'Error al actualizar el producto.'})

@productos_bp.route("/productos/eliminar/<int:id>", methods=['GET'])
def eliminar_producto(id):
    producto = Producto.query.filter_by(id=id).first()
    db.session.delete(producto)
    db.session.commit()
    return jsonify({'Mensaje': 'Producto eliminado con exito.'})

templates/productos/editar_producto.html
{% extends 'base.html'%}
{% block tittle %}
{% endblock %}
{% block content %}
<div class="container-form container">
    <form action="{{ url_for('productos.editar_producto', id=producto.id) }}" method="post">
        <div>
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" value="{{producto.nombre}}">
        </div>
        <div>
            <label for="modelo" class="form-label">Modelo</label>
            <select name="modelo" class="form-select" id="modelo">
                {% for modelo in modelos %}
                    <option value="{{ modelo.id }}" {% if producto.modelo.id == modelo.id %} selected {%endif%}>
                        {{ modelo.nombre }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="precio" class="form-label">Precio</label>
            <input type="number" class="form-control" name="precio" id="precio" value="{{producto.precio}}">
        </div>
        <div>
            <label for="stock" class="form-label">Stock</label>
            <input type="number" class="form-control" name="stock" id="stock" value="{{producto.stock}}">
        </div>
        <div>
            <label for="proveedor" class="form-label">Proveedor</label>
            <select name="proveedor" class="form-select" id="proveedor">
                {% for proveedor in proveedores %}
                    <option value="{{ proveedor.id }}" {% if producto.proveedor.id == proveedor.id %} selected {%endif%}>
                        {{ proveedor.nombre }}
                    </option>
                {%endfor%}
            </select>
        </div>
        <div>
            <label for="categoria" class="form-label">Categoria</label>
            <select name="categoria" class="form-select" id="categoria">
                {% for categoria in categorias %}
                    <option value="{{ categoria.id }}" {% if producto.categoria.id == categoria.id %} selected {%endif%}>
                        {{ categoria.nombre }}
                    </option>
                {%endfor%}
            </select>
        </div>
        <button class="btn btn-primary mt-3" type="submit">Agregar Producto</button>
    </form>
</div>
{%endblock%}

templates/productos/productos.html
{% extends 'base.html'%}
{% block tittle %}<h4>Productos</h4>{% endblock %}
{% block content %}
<div class="productos-container">
    <div class="container-tabla">
        <input type="text" name="" id="" placeholder="Buscar...">
        <table class="table table-striped">
            <thead>
                <th>Nombre</th>
                <th>Modelo</th>
                <th>Precio</th>
                <th>Cantidad disponible</th>
                <th>Proveedor</th>
                <th>Categoria</th>
            </thead>
            <tbody class="table-group-divider">
            {% for producto in productos %}
                <tr>
                    <td>{{producto.nombre}}</td>
                    <td>{{producto.modelo.nombre}}</td>
                    <td>{{producto.precio}}</td>
                    <td>{{producto.stock}}</td>
                    <td>{{producto.proveedor.nombre}}</td>
                    <td>{{producto.categoria.nombre}}</td>
                    <td><a href="{{ url_for('productos.editar_producto', id=producto.id) }}" class="btn btn-success">Editar</a></td>
                    <td><a href="{{ url_for('productos.eliminar_producto', id=producto.id) }}" class="btn btn-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container-form form">
        <form action="productos/crear" method="post">
            <div>
                <label for="nombre" class="form-label">Nombre</label>
                <input type="text" class="form-control" name="nombre" id="nombre">
            </div>
            <div>
                <label for="modelo" class="form-label">Modelo</label>
                <select name="modelo" class="form-select" id="modelo">
                    {% for modelo in modelos %}
                        <option value="{{modelo.id}}">{{modelo.nombre}}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="precio" class="form-label">Precio</label>
                <input type="number" class="form-control" name="precio" id="precio">
            </div>
            <div>
                <label for="stock" class="form-label">Stock</label>
                <input type="number" class="form-control" name="stock" id="stock">
            </div>
            <div>
                <label for="proveedor" class="form-label">Proveedor</label>
                <select name="proveedor" class="form-select" id="proveedor">
                    {% for proveedor in proveedores %}
                    <option value="{{proveedor.id}}">{{proveedor.nombre}}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="categoria" class="form-label">Categoria</label>
                <select name="categoria" class="form-select" id="categoria">
                    {% for categoria in categorias %}
                    <option value="{{categoria.id}}">{{categoria.nombre}}</option>
                    {% endfor %}
                </select>
            </div>
            <button class="btn btn-primary mt-3" type="submit">Agregar Producto</button>
        </form>
    </div>
</div>
{%endblock%}